### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by phuwin1995** [FKK2015/SWED2015#2]

**Comment by phuwin1995** [comment]
a. First task: Write down use cases to evaluate the requirements. (seems to be done)
  b. Please publish your organizational structure and name the selected Process Model!
  c. Setup tools you plan to use during the development, e.g. SCM, programming language, etc., and give an explanation, why you made the selection!
  d. Prepare a documentation structure!
  e. Prepare a first Project Revisit 
The principles of metrics! 
Define suitable metrics for your project, application and development team! 
Perform a first estimation! 
Determine a preliminary project schedule and visualize it!
  f.Please enter a written report about the tasks in the assignment page!
   g. Prepare a presentation of the project status! During the next weeks there will be new tasks with respect to the project!

**Comment by phuwin1995** [comment]
(Phu and Polish Kris)
c.
SCM: Github
We chose Github because it is and a free useful tool for version control during teamwork.
d.
We want to keep records of meetings and decisions on GitHub. If it is required that we need separated documents, we will arrange the meeting memos into pdf files.

**Comment by K-Balabanov** [comment]
Well, guys, I'm working on preparing a  presentation for tomorrow about how far are we with the project. Basically just some info about our organization, process, tools and  I will see how far I can go (maybe metrics and stuff too).

**Comment by PastuszakKrzysztof** [comment]
Is there is something urgent to do this week? As I see there are no new requirements. Would you like to write some code or we are waiting for the next tasks ? BTW thanks for the sample project

**Comment by K-Balabanov** [comment]
He will probably upload a new task sheet today. I think that we should
start coding so we have something on Friday. I have started reworking our
class diagram but maybe I will just  leave it. Since we are doing agile it
is not really important. Look at the project it has quite good examples,
especially for the SDS. You can rework ours to look like those :D (or just
compare, again agile means we don't really care much for modelling) I will
finish the project estimation and schedule. We could do some coding
tomorrow - I have a block from 11.45 until 13.15 and then another from
16.00 until 17.30.
